from __future__ import annotations

CATEGORIES = {
    "scandal",
    "relationships",
    "money",
    "concerts",
    "lifestyle",
    "interviews",
    "social",
    "releases",
    "charity",
    "tv",
    "war",
    "politics",
    "society",
    "economy",
    "world",
    "emergency",
    "health",
    "tech",
    "sports",
    "other",
}

DEFAULT_TRACKED_ENTITIES = [
    {"name": "Jerry Heil", "aliases": ["Jerry Heil", "Джеррі Хейл", "Джерри Хейл"]},
    {"name": "alyona alyona", "aliases": ["alyona alyona", "Альона Альона", "Алена Алена"]},
    {"name": "DOROFEEVA", "aliases": ["DOROFEEVA", "Надя Дорофєєва", "Надя Дорофеева", "Дорофєєва", "Дорофеева"]},
    {"name": "Tina Karol", "aliases": ["Tina Karol", "Тіна Кароль", "Тина Кароль"]},
    {"name": "Anna Trincher", "aliases": ["Anna Trincher", "Анна Трінчер", "Анна Тринчер"]},
    {"name": "KOLA", "aliases": ["KOLA", "Кола", "Анастасія Прудіус", "Анастасия Прудиус"]},
    {"name": "FIЇNKA", "aliases": ["FIЇNKA", "FIINKA", "Фіїнка", "Фиинка"]},
    {"name": "Olya Polyakova", "aliases": ["Olya Polyakova", "Оля Полякова", "Ольга Полякова"]},
    {"name": "Zlata Ognevich", "aliases": ["Zlata Ognevich", "Злата Огневич", "Злата Огнєвіч"]},
    {"name": "MAMARIKA", "aliases": ["MAMARIKA", "MamaRika", "Мамаріка", "Мамарика"]},
    {"name": "YAKTAK", "aliases": ["YAKTAK", "Яктак", "Ярослав Карпук"]},
    {"name": "Artem Pivovarov", "aliases": ["Artem Pivovarov", "Артем Пивоваров"]},
    {"name": "MÉLOVIN", "aliases": ["MÉLOVIN", "MELOVIN", "Меловін", "Меловин", "Костянтин Бочаров"]},
    {"name": "SKOFKA", "aliases": ["SKOFKA", "Скофка", "Володимир Самолюк"]},
    {"name": "Kalush Orchestra", "aliases": ["Kalush Orchestra", "Калуш Оркестра", "Kalush"]},
    {"name": "Okean Elzy", "aliases": ["Okean Elzy", "Океан Ельзи", "Океан Эльзы", "Святослав Вакарчук"]},
    {"name": "Klavdia Petrivna", "aliases": ["Klavdia Petrivna", "Клавдія Петрівна", "Клавдия Петровна"]},
    {"name": "MONATIK", "aliases": ["MONATIK", "Monatik", "Монатік", "Монатик", "Дмитро Монатік", "Дмитрий Монатик"]},
    {"name": "Max Barskih", "aliases": ["Max Barskih", "MAX BARSKIH", "Макс Барських", "Макс Барских", "Микола Бортник", "Николай Бортник"]},
    {"name": "NK", "aliases": ["NK", "Настя Каменських", "Настя Каменских", "Nastya Kamenskykh", "Kamenskykh", "Каменських", "Каменских"]},
    {"name": "Ivan NAVI", "aliases": ["Ivan NAVI", "Іван NAVI", "Иван NAVI", "Іван Наві", "Иван Нави", "Іван Сяркевич", "Иван Сяркевич"]},
    {"name": "Wellboy", "aliases": ["Wellboy", "Веллбой", "Велбой", "Антон Вельбой", "Антон Вельбой"]},
    {"name": "Parfeniuk", "aliases": ["Parfeniuk", "Парфенюк", "Ілля Парфенюк", "Илья Парфенюк", "Ilya Parfeniuk", "Illia Parfeniuk"]},
    {"name": "SadSvit", "aliases": ["SadSvit", "Sadsvit", "СадСвіт", "СадСвит", "Богдан Розвадовський", "Богдан Розвадовский"]},
    {"name": "DOVI", "aliases": ["DOVI", "Dovi", "Дові", "Дови", "Дмитро Нечипоренко", "Дмитрий Нечипоренко"]},
    {"name": "Iryna Bilyk", "aliases": ["Iryna Bilyk", "Ірина Білик", "Ирина Билык", "Irina Bilyk", "Білик", "Билык"]},
    {"name": "Verka Serduchka", "aliases": ["Verka Serduchka", "Вєрка Сердючка", "Верка Сердючка", "Андрій Данилко", "Андрей Данилко"]},
    {"name": "Sofia Rotaru", "aliases": ["Sofia Rotaru", "Софія Ротару", "София Ротару", "Sofiya Rotaru", "Ротару"]},
    {"name": "The Hardkiss", "aliases": ["The Hardkiss", "THE HARDKISS", "Хардкіс", "Хардкис", "Юлія Саніна", "Юлия Санина", "Yulia Sanina"]},
    {"name": "Antytila", "aliases": ["Antytila", "Антитіла", "Антитела", "Тарас Тополя", "Taras Topolia", "Taras Topolya"]},
    {"name": "KAZKA", "aliases": ["KAZKA", "Kazka", "Казка", "Олександра Заріцька", "Александра Зарицкая", "Zaritska"]},
    {"name": "Alina Grosu", "aliases": ["Аліна Гросу", "Алина Гросу", "Alina Grosu", "Grosu", "Гросу"]},
    {"name": "Lesia Nikitiuk", "aliases": ["Леся Нікітюк", "Леся Никитюк", "Lesia Nikitiuk", "Lesya Nikityuk", "Нікітюк", "Никитюк"]},
    {"name": "Nadiia Khilska", "aliases": ["Надія Хільська", "Надежда Хильская", "Nadiia Khilska", "Nadia Khilska", "Хільська", "Хильская"]},
    {"name": "Natalka Denysenko", "aliases": ["Наталка Денисенко", "Наталія Денисенко", "Наталка Денисенко", "Natalka Denysenko", "Natalia Denysenko", "Денисенко"]},
    {"name": "Taras Tsymbaliuk", "aliases": ["Тарас Цимбалюк", "Тарас Цымбалюк", "Taras Tsymbaliuk", "Taras Tsymbalyuk", "Цимбалюк", "Цымбалюк"]},
    {"name": "Hryhorii Reshetnik", "aliases": ["Григорій Решетнік", "Григорий Решетник", "Hryhorii Reshetnik", "Grigoriy Reshetnik", "Решетнік", "Решетник"]},
    {"name": "Daria Trehubova", "aliases": ["Дар'я Трегубова", "Дар’я Трегубова", "Дарья Трегубова", "Daria Trehubova", "Darya Tregubova", "Трегубова"]},
    {"name": "Oleksandr Teren", "aliases": ["Олександр Терен", "Александр Терен", "Oleksandr Teren", "Alexander Teren", "Терен"]},
    {"name": "Olena Topolia", "aliases": ["Олена Тополя", "Елена Тополя", "Olena Topolia", "Elena Topolya", "Тополя"]},
    {"name": "Jamala", "aliases": ["Jamala", "Джамала", "Сусана Джамаладінова", "Сусана Джамаладинова"]},
    {"name": "DZIDZIO", "aliases": ["DZIDZIO", "Dzidzio", "Дзідзьо", "Дзидзьо", "Михайло Хома", "Михаил Хома"]},
    {"name": "Potap", "aliases": ["Potap", "Потап", "Олексій Потапенко", "Алексей Потапенко"]},
    {"name": "Iryna Fedyshyn", "aliases": ["Ірина Федишин", "Ирина Федишин", "Iryna Fedyshyn", "Irina Fedyshyn", "Федишин"]},
    {"name": "Oleh Vynnyk", "aliases": ["Олег Винник", "Oleh Vynnyk", "Oleg Vynnyk", "Винник"]},
    {"name": "Masha Efrosinina", "aliases": ["Маша Єфросиніна", "Маша Ефросініна", "Маша Ефросинина", "Марія Єфросиніна", "Мария Ефросинина", "Masha Efrosinina", "Masha Yefrosinina", "Maria Efrosinina", "Єфросиніна", "Ефросинина"]},
    {"name": "Taisia Povaliy", "aliases": ["Таїсія Повалій", "Таисия Повалий", "Taisia Povaliy", "Taisiya Povaliy", "Taisia Povalii", "Повалій", "Повалий"]},
    {"name": "LOBODA", "aliases": ["LOBODA", "Loboda", "Світлана Лобода", "Светлана Лобода", "Svitlana Loboda", "Svetlana Loboda", "Лобода"]},
    {"name": "Olia Tsybulska", "aliases": ["Оля Цибульська", "Ольга Цибульська", "Оля Цибульская", "Ольга Цибульская", "Olia Tsybulska", "Olya Tsybulskaya", "Tsybulska", "Цибульська", "Цибульская"]},
    {"name": "Nataliia Mohylevska", "aliases": ["Наталія Могилевська", "Наталья Могилевская", "Nataliia Mohylevska", "Natalia Mogilevskaya", "Могилевська", "Могилевская"]},
    {"name": "Alyosha", "aliases": ["Alyosha", "ALYOSHA", "Альоша", "Алеша", "Олена Тополя", "Елена Тополя", "Olena Topolia", "Elena Topolya"]},
    {"name": "Tonia Matviienko", "aliases": ["Тоня Матвієнко", "Антоніна Матвієнко", "Тоня Матвиенко", "Антонина Матвиенко", "Tonia Matviienko", "Tonya Matvienko", "Матвієнко", "Матвиенко"]},
    {"name": "Arsen Mirzoyan", "aliases": ["Арсен Мірзоян", "Арсен Мирзоян", "Arsen Mirzoyan", "Arsen Mirzoian", "Мірзоян", "Мирзоян"]},
    {"name": "Michelle Andrade", "aliases": ["Мішель Андраде", "Мишель Андраде", "Michelle Andrade", "Мішель", "Мишель", "Андраде"]},
    {"name": "Volodymyr Ostapchuk", "aliases": ["Володимир Остапчук", "Владимир Остапчук", "Volodymyr Ostapchuk", "Vladimir Ostapchuk", "Остапчук"]},
    {"name": "Kateryna Osadcha", "aliases": ["Катерина Осадча", "Екатерина Осадчая", "Kateryna Osadcha", "Ekaterina Osadchaya", "Осадча", "Осадчая"]},
    {"name": "Yurii Horbunov", "aliases": ["Юрій Горбунов", "Юрий Горбунов", "Yurii Horbunov", "Yuri Gorbunov", "Горбунов"]},
    {"name": "Volodymyr Dantes", "aliases": ["Володимир Дантес", "Владимир Дантес", "Volodymyr Dantes", "Vladimir Dantes", "Дантес", "Dantes"]},
    {"name": "Slava Diomin", "aliases": ["Слава Дьомін", "Слава Демин", "Слава Дёмин", "Slava Diomin", "Slava Demin", "Дьомін", "Демин", "Дёмин"]},
    {"name": "Hector Jimenez-Bravo", "aliases": ["Ектор Хіменес-Браво", "Эктор Хименес-Браво", "Hector Jimenez-Bravo", "Héctor Jiménez-Bravo", "Ектор", "Эктор", "Хіменес-Браво", "Хименес-Браво"]},
    {"name": "Ksenia Mishyna", "aliases": ["Ксенія Мішина", "Ксения Мишина", "Ksenia Mishyna", "Kseniya Mishina", "Мішина", "Мишина"]},
    {"name": "Olha Sumska", "aliases": ["Ольга Сумська", "Ольга Сумская", "Olha Sumska", "Olga Sumskaya", "Сумська", "Сумская"]},
    {"name": "Dasha Astafieva", "aliases": ["Даша Астаф’єва", "Даша Астафьева", "Дар'я Астаф’єва", "Дарья Астафьева", "Dasha Astafieva", "Daria Astafieva", "Астаф’єва", "Астафьева"]},
    {"name": "Santa Dimopulos", "aliases": ["Санта Дімопулос", "Санта Димопулос", "Santa Dimopulos", "Santa Dimopoulos", "Дімопулос", "Димопулос"]},
    {"name": "Sonia Yevdokymenko", "aliases": ["Соня Євдокименко", "Софія Євдокименко", "Соня Евдокименко", "София Евдокименко", "Sonia Yevdokymenko", "Sofia Yevdokymenko", "Sofia Evdokimenko", "Євдокименко", "Евдокименко"]},
    {"name": "Boombox", "aliases": ["Бумбокс", "Boombox", "БумБокс", "Андрій Хливнюк", "Андрей Хлывнюк", "Andrii Khlyvniuk", "Хливнюк", "Хлывнюк"]},
    {"name": "DakhaBrakha", "aliases": ["ДахаБраха", "DakhaBrakha", "Dakha Brakha", "Даха Браха"]},
    {"name": "Bez Obmezhen", "aliases": ["Без Обмежень", "Без Обмежень", "Bez Obmezhen", "Без Ограничений", "Сергій Танчинець", "Сергей Танчинец", "Танчинець", "Танчинец"]},
    {"name": "TNMK", "aliases": ["ТНМК", "TNMK", "Танок на майдані Конґо", "Танок на майдане Конго", "Фагот", "Олег Михайлюта", "Фоззі", "Fozzy"]},
    {"name": "Khrystyna Soloviy", "aliases": ["Христина Соловій", "Кристина Соловий", "Khrystyna Soloviy", "Khrystyna Solovii", "Соловій", "Соловий"]},
    {"name": "Go_A", "aliases": ["Go_A", "Go-A", "Го_А", "Го-А", "Катерина Павленко", "Екатерина Павленко", "Kateryna Pavlenko"]},
    {"name": "ONUKA", "aliases": ["ONUKA", "Onuka", "Онука", "Ната Жижченко", "Наталія Жижченко", "Ната Жижченко"]},
    {"name": "Pianoboy", "aliases": ["Pianoбой", "Pianoboy", "Піанобой", "Пианобой", "Дмитро Шуров", "Дмитрий Шуров", "Шуров"]},
]

DEFAULT_SOURCES = [
    {
        "name": "TSN Glamur",
        "base_url": "https://tsn.ua/glamur",
        "type": "html",
        "priority": 90,
        "credibility_score": 82,
        "entertainment_bias_score": 92,
    },
    {
        "name": "UNIAN Lite Stars",
        "base_url": "https://www.unian.ua/lite/stars",
        "type": "html",
        "priority": 82,
        "credibility_score": 78,
        "entertainment_bias_score": 88,
    },
    {
        "name": "Oboz Show",
        "base_url": "https://www.obozrevatel.com/ukr/shou-oboz/",
        "type": "html",
        "priority": 76,
        "credibility_score": 72,
        "entertainment_bias_score": 85,
    },
    {
        "name": "Lux FM Stars",
        "base_url": "https://lux.fm/stars_t25",
        "type": "html",
        "priority": 74,
        "credibility_score": 70,
        "entertainment_bias_score": 92,
    },
    {
        "name": "Viva Stars",
        "base_url": "https://viva.ua/stars",
        "type": "html",
        "priority": 70,
        "credibility_score": 68,
        "entertainment_bias_score": 86,
    },
    {
        "name": "Concert.ua Concerts",
        "base_url": "https://concert.ua/uk/catalog/kyiv/concerts",
        "type": "ticket_html",
        "priority": 88,
        "credibility_score": 90,
        "entertainment_bias_score": 95,
    },
    {
        "name": "Karabas Concerts",
        "base_url": "https://karabas.com/ua/ua/concerts/",
        "type": "ticket_html",
        "priority": 84,
        "credibility_score": 86,
        "entertainment_bias_score": 94,
    },
    {
        "name": "Kontramarka Concerts",
        "base_url": "https://kontramarka.ua/uk/concert",
        "type": "ticket_html",
        "priority": 82,
        "credibility_score": 84,
        "entertainment_bias_score": 92,
    },
    {
        "name": "TicketsBox Events",
        "base_url": "https://ticketsbox.com/uk/",
        "type": "ticket_html",
        "priority": 80,
        "credibility_score": 82,
        "entertainment_bias_score": 90,
    },
    {
        "name": "ICTV Fakty Entertainment",
        "base_url": "https://fakty.com.ua/ua/showbiz/",
        "type": "html",
        "priority": 84,
        "credibility_score": 82,
        "entertainment_bias_score": 80,
    },
    {
        "name": "Novyny LIVE Showbiz",
        "base_url": "https://showbiz.novyny.live/",
        "type": "html",
        "priority": 78,
        "credibility_score": 72,
        "entertainment_bias_score": 88,
    },
    {
        "name": "RBC Ukraine Lite",
        "base_url": "https://lite.rbc.ua/",
        "type": "html",
        "priority": 86,
        "credibility_score": 84,
        "entertainment_bias_score": 84,
    },
    {
        "name": "Clutch Showbiz",
        "base_url": "https://clutch.net.ua/showbiz",
        "type": "html",
        "priority": 66,
        "credibility_score": 58,
        "entertainment_bias_score": 88,
    },
    {
        "name": "Glavred Stars",
        "base_url": "https://stars.glavred.info/",
        "type": "html",
        "priority": 64,
        "credibility_score": 56,
        "entertainment_bias_score": 86,
    },
    {
        "name": "1plus1 Star Life",
        "base_url": "https://1plus1.ua/tag/zirkove-zitta",
        "type": "html",
        "priority": 80,
        "credibility_score": 78,
        "entertainment_bias_score": 82,
    },
    {
        "name": "1plus1 Show",
        "base_url": "https://1plus1.ua/tag/show",
        "type": "html",
        "priority": 72,
        "credibility_score": 76,
        "entertainment_bias_score": 74,
    },
    {
        "name": "Tabloid Pravda",
        "base_url": "https://tabloid.pravda.com.ua/",
        "type": "html",
        "priority": 88,
        "credibility_score": 82,
        "entertainment_bias_score": 90,
    },
    {
        "name": "NV Life Celebrities",
        "base_url": "https://life.nv.ua/ukr/znamenitosti.html",
        "type": "html",
        "priority": 82,
        "credibility_score": 82,
        "entertainment_bias_score": 84,
    },
    {
        "name": "Insider UA",
        "base_url": "https://insider.ua/",
        "type": "html",
        "priority": 78,
        "credibility_score": 72,
        "entertainment_bias_score": 86,
    },
    {
        "name": "UKR.NET Show Business",
        "base_url": "https://www.ukr.net/news/show_business.html",
        "type": "html",
        "priority": 76,
        "credibility_score": 70,
        "entertainment_bias_score": 92,
    },
    {
        "name": "Novyny LIVE Stars",
        "base_url": "https://novyny.live/zirki",
        "type": "html",
        "priority": 75,
        "credibility_score": 72,
        "entertainment_bias_score": 90,
    },
    {
        "name": "Zirky Showbiz",
        "base_url": "https://zirky.com.ua/category/shoubiznes/",
        "type": "html",
        "priority": 70,
        "credibility_score": 64,
        "entertainment_bias_score": 92,
    },
    {
        "name": "Odna Hvylyna Showbiz",
        "base_url": "https://odnaminyta.com/shou-biznes",
        "type": "html",
        "priority": 55,
        "credibility_score": 48,
        "entertainment_bias_score": 88,
    },
    {
        "name": "Ukrainska Pravda News",
        "base_url": "https://www.pravda.com.ua/news/",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 96,
        "credibility_score": 92,
        "entertainment_bias_score": 20,
    },
    {
        "name": "Suspilne News",
        "base_url": "https://suspilne.media/news/",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 94,
        "credibility_score": 94,
        "entertainment_bias_score": 18,
    },
    {
        "name": "TSN Ukraine News",
        "base_url": "https://tsn.ua/ukrayina",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 90,
        "credibility_score": 80,
        "entertainment_bias_score": 22,
    },
    {
        "name": "UNIAN News",
        "base_url": "https://www.unian.ua/news",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 88,
        "credibility_score": 78,
        "entertainment_bias_score": 22,
    },
    {
        "name": "RBC Ukraine News",
        "base_url": "https://www.rbc.ua/rus/news",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 88,
        "credibility_score": 82,
        "entertainment_bias_score": 22,
    },
    {
        "name": "NV Ukraine News",
        "base_url": "https://nv.ua/ukr/ukraine.html",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 84,
        "credibility_score": 82,
        "entertainment_bias_score": 20,
    },
    {
        "name": "Liga News",
        "base_url": "https://news.liga.net/ua",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 84,
        "credibility_score": 84,
        "entertainment_bias_score": 18,
    },
    {
        "name": "Hromadske News",
        "base_url": "https://hromadske.ua/",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 82,
        "credibility_score": 84,
        "entertainment_bias_score": 18,
    },
    {
        "name": "BBC Ukraine",
        "base_url": "https://www.bbc.com/ukrainian",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 82,
        "credibility_score": 90,
        "entertainment_bias_score": 15,
    },
    {
        "name": "Ukrinform News",
        "base_url": "https://www.ukrinform.ua/",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 80,
        "credibility_score": 82,
        "entertainment_bias_score": 18,
    },
    {
        "name": "24 Kanal News",
        "base_url": "https://24tv.ua/",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 78,
        "credibility_score": 74,
        "entertainment_bias_score": 20,
    },
    {
        "name": "ZN UA News",
        "base_url": "https://zn.ua/ukr/",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 86,
        "credibility_score": 84,
        "entertainment_bias_score": 12,
    },
    {
        "name": "LB.ua News",
        "base_url": "https://lb.ua/",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 84,
        "credibility_score": 82,
        "entertainment_bias_score": 14,
    },
    {
        "name": "Babel News",
        "base_url": "https://babel.ua/news",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 84,
        "credibility_score": 82,
        "entertainment_bias_score": 18,
    },
    {
        "name": "Radio Svoboda News",
        "base_url": "https://www.radiosvoboda.org/",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 82,
        "credibility_score": 88,
        "entertainment_bias_score": 12,
    },
    {
        "name": "Espreso News",
        "base_url": "https://espreso.tv/",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 78,
        "credibility_score": 76,
        "entertainment_bias_score": 18,
    },
    {
        "name": "Interfax Ukraine News",
        "base_url": "https://interfax.com.ua/news/latest.html",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 78,
        "credibility_score": 84,
        "entertainment_bias_score": 10,
    },
    {
        "name": "Censor.NET News",
        "base_url": "https://censor.net/ua/news/all",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 74,
        "credibility_score": 70,
        "entertainment_bias_score": 12,
    },
    {
        "name": "Korrespondent News",
        "base_url": "https://ua.korrespondent.net/",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 72,
        "credibility_score": 68,
        "entertainment_bias_score": 18,
    },
    {
        "name": "Detector Media News",
        "base_url": "https://detector.media/",
        "type": "news_html",
        "group": "news",
        "enabled": 0,
        "priority": 70,
        "credibility_score": 76,
        "entertainment_bias_score": 16,
    },
    {
        "name": "ICTV Fakty News",
        "base_url": "https://fakty.com.ua/ua/ukraine/",
        "type": "news_html",
        "group": "news_telethon",
        "enabled": 0,
        "priority": 68,
        "credibility_score": 76,
        "entertainment_bias_score": 18,
    },
    {
        "name": "1plus1 TSN Main News",
        "base_url": "https://tsn.ua/",
        "type": "news_html",
        "group": "news_telethon",
        "enabled": 0,
        "priority": 66,
        "credibility_score": 76,
        "entertainment_bias_score": 22,
    },
    {
        "name": "Rada News",
        "base_url": "https://www.rada.gov.ua/news/Novyny/",
        "type": "news_html",
        "group": "news_telethon",
        "enabled": 0,
        "priority": 62,
        "credibility_score": 78,
        "entertainment_bias_score": 8,
    },
    {
        "name": "Dim UATV News",
        "base_url": "https://kanaldim.tv/novyny/",
        "type": "news_html",
        "group": "news_telethon",
        "enabled": 0,
        "priority": 60,
        "credibility_score": 72,
        "entertainment_bias_score": 14,
    },
    {
        "name": "Freedom UATV News",
        "base_url": "https://uatv.ua/uk/category/novini/",
        "type": "news_html",
        "group": "news_telethon",
        "enabled": 0,
        "priority": 58,
        "credibility_score": 70,
        "entertainment_bias_score": 14,
    },
    {
        "name": "We Ukraine News",
        "base_url": "https://weukraine.tv/novyny/",
        "type": "news_html",
        "group": "news_telethon",
        "enabled": 0,
        "priority": 58,
        "credibility_score": 70,
        "entertainment_bias_score": 16,
    },
    {
        "name": "Podrobnosti News",
        "base_url": "https://podrobnosti.ua/",
        "type": "news_html",
        "group": "news_telethon",
        "enabled": 0,
        "priority": 52,
        "credibility_score": 62,
        "entertainment_bias_score": 16,
    },
    {
        "name": "Instagram Social",
        "base_url": "https://www.instagram.com/",
        "type": "social_instagram",
        "enabled": 0,
        "priority": 92,
        "credibility_score": 55,
        "entertainment_bias_score": 100,
    },
]

RELATIONSHIP_KEYWORDS = {
    "развод",
    "розлуч",
    "свадь",
    "весіл",
    "женил",
    "замуж",
    "кохан",
    "любов",
    "роман",
    "бойфренд",
    "муж",
    "чоловік",
    "жена",
    "дружина",
}
MONEY_KEYWORDS = {"гонорар", "зароб", "деньг", "гроші", "миллион", "мільйон", "доход", "квартир", "дом", "майно"}
CONCERT_KEYWORDS = {"концерт", "гастрол", "виступ", "выступ", "сцена", "квитк", "билет", "open air"}
SCANDAL_KEYWORDS = {"скандал", "хейт", "критик", "зрад", "ссор", "свар", "обур", "конфликт", "конфлікт"}
SOCIAL_KEYWORDS = {"instagram", "інстаграм", "тикток", "tiktok", "сторіс", "stories", "пост", "соцмереж"}
RELEASE_KEYWORDS = {"пісн", "песня", "клип", "кліп", "альбом", "реліз", "трек", "дует"}
INTERVIEW_KEYWORDS = {"інтерв", "интерв", "розпов", "рассказ", "зізнал", "признал"}
LIFESTYLE_KEYWORDS = {"образ", "лук", "фото", "відпоч", "отдых", "діти", "дети", "життя", "жизнь"}
CHARITY_KEYWORDS = {"благодійн", "благотвор", "донат", "збір", "сбор", "зсу", "військ", "военн"}
TV_KEYWORDS = {"шоу", "ефір", "эфир", "телепроєкт", "телепроект", "серіал", "сериал", "голос країни", "танці з зірками"}
WAR_KEYWORDS = {"війна", "військ", "фронт", "зсу", "атака", "обстріл", "дрон", "шахед", "ракета", "окупант", "загиб", "поран"}
POLITICS_KEYWORDS = {"зеленськ", "рада", "уряд", "президент", "міністр", "парламент", "вибор", "закон", "політик", "переговор", "партія"}
ECONOMY_KEYWORDS = {"економ", "гривн", "долар", "євро", "банк", "подат", "бюджет", "інфляц", "ціни", "тариф"}
WORLD_KEYWORDS = {"сша", "єс", "нато", "трамп", "польщ", "німеч", "франц", "китай", "світ", "міжнарод", "москва", "москв", "росі", "рф"}
EMERGENCY_KEYWORDS = {"вибух", "пожеж", "дтп", "авар", "теракт", "стрілян", "катастроф", "надзвичай"}
HEALTH_KEYWORDS = {"лікар", "здоров", "хвор", "вірус", "медиц", "лікарн", "депрес", "серц"}
TECH_KEYWORDS = {"технолог", "штучн", "інтелект", "дрон", "кібер", "хакер", "стартап", "застосунок"}
SPORTS_KEYWORDS = {"спорт", "футбол", "бокс", "олімп", "матч", "чемпіон", "перемог"}
