CREATE TABLE IF NOT EXISTS sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    base_url TEXT NOT NULL,
    type TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    priority INTEGER NOT NULL DEFAULT 50,
    credibility_score INTEGER NOT NULL DEFAULT 70,
    entertainment_bias_score INTEGER NOT NULL DEFAULT 70,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tracked_entities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    entity_type TEXT NOT NULL DEFAULT 'person',
    aliases_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS discovered_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT REFERENCES sources(id),
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    canonical_url TEXT NOT NULL,
    published_at TEXT,
    raw_snippet TEXT,
    raw_body TEXT,
    matched_entities_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    category TEXT NOT NULL DEFAULT 'other',
    fingerprint TEXT NOT NULL UNIQUE,
    similarity_key TEXT NOT NULL,
    primary_entity TEXT,
    relevance_score INTEGER NOT NULL DEFAULT 0,
    relevance_explanation TEXT,
    is_primary_story BOOLEAN NOT NULL DEFAULT TRUE,
    duplicate_group_id BIGINT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_discovered_status ON discovered_items(status);
CREATE INDEX IF NOT EXISTS idx_discovered_similarity ON discovered_items(similarity_key);
CREATE INDEX IF NOT EXISTS idx_discovered_canonical ON discovered_items(canonical_url);

CREATE TABLE IF NOT EXISTS published_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discovered_item_id BIGINT UNIQUE REFERENCES discovered_items(id),
    telegram_message_id BIGINT,
    telegram_chat_id TEXT,
    published_text TEXT NOT NULL,
    published_at TEXT NOT NULL,
    category TEXT,
    post_type TEXT NOT NULL DEFAULT 'organic',
    artist_main TEXT,
    source_name TEXT,
    views INTEGER,
    forwards INTEGER,
    reactions INTEGER,
    ad_slots_sold INTEGER DEFAULT 0,
    affiliate_clicks INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS system_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TEXT NOT NULL,
    finished_at TEXT,
    scanned_sources INTEGER NOT NULL DEFAULT 0,
    discovered_count INTEGER NOT NULL DEFAULT 0,
    relevant_count INTEGER NOT NULL DEFAULT 0,
    published_count INTEGER NOT NULL DEFAULT 0,
    error_count INTEGER NOT NULL DEFAULT 0,
    notes TEXT
);
